"""Add discount_usd + discount_code to Order

Revision ID: 04a99fb69915
Revises: fbe1593b2171
Create Date: 2025-07-14 19:35:32.096202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a99fb69915'
down_revision = 'fbe1593b2171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_usd', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_usd')
    # ### end Alembic commands ###
