"""orders+affiliates+commissions

Revision ID: 4617f8b850fa
Revises: c59d84d9f368
Create Date: 2025-07-13 18:07:44.196403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4617f8b850fa'
down_revision = 'c59d84d9f368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('btc_address', sa.String(length=128), nullable=True),
    sa.Column('xmr_address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('usd_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('btc_amount', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('xmr_amount', sa.Numeric(precision=20, scale=12), nullable=True),
    sa.Column('btc_address', sa.String(length=128), nullable=True),
    sa.Column('xmr_address', sa.String(length=128), nullable=True),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('discount_code', sa.String(length=32), nullable=True),
    sa.Column('commission_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('btc_address'),
    sa.UniqueConstraint('xmr_address')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('usd_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissions')
    op.drop_table('orders')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
