"""Add txid & paid_ts to Commission

Revision ID: 619d98e06656
Revises: 04a99fb69915
Create Date: 2025-07-14 20:16:56.179602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619d98e06656'
down_revision = '04a99fb69915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commissions', sa.Column('txid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commissions', 'txid')
    # ### end Alembic commands ###
