"""Add affiliates, commissions, and extend orders

Revision ID: b7b2a70a106d
Revises: 4617f8b850fa
Create Date: 2025-07-13 18:54:01.870470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b2a70a106d'
down_revision = '4617f8b850fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
