"""Add hd_index to Order

Revision ID: bd7d92c511bd
Revises: 619d98e06656
Create Date: 2025-07-15 19:29:04.691612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7d92c511bd'
down_revision = '619d98e06656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
