"""Add hd_index to Order

Revision ID: c778372bd554
Revises: bd7d92c511bd
Create Date: 2025-07-15 19:40:44.194480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c778372bd554'
down_revision = 'bd7d92c511bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('hd_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'hd_index')
    # ### end Alembic commands ###
