"""Add role and affiliate_id to User

Revision ID: d1f19e4bf2d4
Revises: b7b2a70a106d
Create Date: 2025-07-13 21:24:09.701798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f19e4bf2d4'
down_revision = 'b7b2a70a106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=16), nullable=False))
    op.add_column('users', sa.Column('affiliate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'affiliates', ['affiliate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'affiliate_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
