"""Add discount_usd to Order

Revision ID: fbe1593b2171
Revises: 2de774ede7cb
Create Date: 2025-07-14 19:17:29.653126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe1593b2171'
down_revision = '2de774ede7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
